PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS workspaces(id TEXT PRIMARY KEY, name TEXT NOT NULL, manual_seconds INTEGER NOT NULL DEFAULT 30 CHECK(manual_seconds BETWEEN 1 AND 3600));
CREATE TABLE IF NOT EXISTS owners(id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL REFERENCES workspaces(id));
CREATE TABLE IF NOT EXISTS devices(token_hash TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),created_at TEXT NOT NULL,revoked_at TEXT);
CREATE TABLE IF NOT EXISTS pairing_codes(code_hash TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),expires_at TEXT NOT NULL,used_at TEXT);
CREATE TABLE IF NOT EXISTS oauth_states(state_hash TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),expires_at TEXT NOT NULL,used_at TEXT);
CREATE TABLE IF NOT EXISTS social_accounts(id TEXT PRIMARY KEY,workspace_id TEXT NOT NULL REFERENCES workspaces(id),provider TEXT NOT NULL,provider_id TEXT NOT NULL,username TEXT NOT NULL,status TEXT NOT NULL,token_ciphertext TEXT,token_expires_at TEXT,UNIQUE(provider,provider_id));
CREATE TABLE IF NOT EXISTS media(id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES social_accounts(id),provider_id TEXT NOT NULL,caption TEXT NOT NULL,type TEXT NOT NULL,published_at TEXT NOT NULL,views INTEGER,thumbnail_url TEXT,permalink TEXT,collected_at TEXT,UNIQUE(account_id,provider_id));
CREATE TABLE IF NOT EXISTS campaigns(id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES social_accounts(id),name TEXT NOT NULL,trigger TEXT NOT NULL CHECK(trigger IN ('comment','dm')),media_id TEXT REFERENCES media(id),message TEXT NOT NULL,destination_url TEXT NOT NULL,state TEXT NOT NULL CHECK(state IN ('Draft','Active','Paused','Error')),fuzzy INTEGER NOT NULL DEFAULT 1,cooldown_hours REAL NOT NULL DEFAULT 24,activated_at TEXT NOT NULL,created_at TEXT NOT NULL,exclusions TEXT NOT NULL DEFAULT '[]');
CREATE TABLE IF NOT EXISTS campaign_keywords(id TEXT PRIMARY KEY,campaign_id TEXT NOT NULL REFERENCES campaigns(id),keyword TEXT NOT NULL,UNIQUE(campaign_id,keyword));
CREATE TABLE IF NOT EXISTS people(id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES social_accounts(id),provider_id TEXT NOT NULL,username TEXT,created_at TEXT NOT NULL,UNIQUE(account_id,provider_id));
CREATE TABLE IF NOT EXISTS blocked_people(person_id TEXT PRIMARY KEY REFERENCES people(id),created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS incoming_events(id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES social_accounts(id),provider_event_id TEXT NOT NULL,person_id TEXT REFERENCES people(id),media_id TEXT REFERENCES media(id),kind TEXT NOT NULL,text TEXT NOT NULL,occurred_at TEXT NOT NULL,received_at TEXT NOT NULL,top_level INTEGER,own INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'received',reason TEXT,campaign_id TEXT REFERENCES campaigns(id),keyword TEXT,UNIQUE(account_id,provider_event_id));
CREATE TABLE IF NOT EXISTS messages(id TEXT PRIMARY KEY,event_id TEXT NOT NULL UNIQUE REFERENCES incoming_events(id),campaign_id TEXT NOT NULL REFERENCES campaigns(id),person_id TEXT NOT NULL REFERENCES people(id),media_id TEXT REFERENCES media(id),body TEXT NOT NULL,status TEXT NOT NULL,provider_message_id TEXT,sent_at TEXT,created_at TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,claimed_at TEXT,next_attempt_at TEXT,error_kind TEXT,error_detail TEXT);
CREATE TABLE IF NOT EXISTS send_attempts(id TEXT PRIMARY KEY,message_id TEXT NOT NULL REFERENCES messages(id),started_at TEXT NOT NULL,result TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS cooldowns(person_id TEXT NOT NULL REFERENCES people(id),campaign_id TEXT NOT NULL REFERENCES campaigns(id),message_id TEXT NOT NULL,until_at TEXT NOT NULL,PRIMARY KEY(person_id,campaign_id));
CREATE TABLE IF NOT EXISTS link_redirects(token TEXT PRIMARY KEY,message_id TEXT NOT NULL UNIQUE REFERENCES messages(id),campaign_id TEXT NOT NULL REFERENCES campaigns(id),person_id TEXT NOT NULL REFERENCES people(id),media_id TEXT REFERENCES media(id),destination_url TEXT NOT NULL,created_at TEXT NOT NULL,first_clicked_at TEXT,click_count INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS click_events(id TEXT PRIMARY KEY,token TEXT NOT NULL REFERENCES link_redirects(token),occurred_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS conversation_events(id TEXT PRIMARY KEY,event_id TEXT NOT NULL UNIQUE REFERENCES incoming_events(id),message_id TEXT NOT NULL REFERENCES messages(id),person_id TEXT NOT NULL REFERENCES people(id),occurred_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS activity(id TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES social_accounts(id),person_id TEXT REFERENCES people(id),campaign_id TEXT REFERENCES campaigns(id),event_id TEXT,kind TEXT NOT NULL,description TEXT NOT NULL,occurred_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS outbox(event_id TEXT PRIMARY KEY REFERENCES incoming_events(id),published_at TEXT,created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_accounts_workspace ON social_accounts(workspace_id);
CREATE INDEX IF NOT EXISTS idx_campaigns_account ON campaigns(account_id,state,trigger,media_id);
CREATE INDEX IF NOT EXISTS idx_events_person ON incoming_events(person_id,occurred_at);
CREATE INDEX IF NOT EXISTS idx_events_campaign ON incoming_events(campaign_id,status);
CREATE INDEX IF NOT EXISTS idx_messages_person ON messages(person_id,sent_at);
CREATE INDEX IF NOT EXISTS idx_messages_state ON messages(status,next_attempt_at);
CREATE INDEX IF NOT EXISTS idx_redirects_campaign ON link_redirects(campaign_id,first_clicked_at);
CREATE INDEX IF NOT EXISTS idx_conversation_message ON conversation_events(message_id);
CREATE INDEX IF NOT EXISTS idx_activity_account ON activity(account_id,occurred_at);
CREATE INDEX IF NOT EXISTS idx_outbox_pending ON outbox(published_at);

CREATE TABLE IF NOT EXISTS webhook_receipts(id TEXT PRIMARY KEY,payload TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,error_detail TEXT);
CREATE INDEX IF NOT EXISTS idx_receipts_status ON webhook_receipts(status,created_at);
CREATE TABLE IF NOT EXISTS sync_state(account_id TEXT PRIMARY KEY REFERENCES social_accounts(id),next_sync_at TEXT NOT NULL,last_error TEXT);

CREATE INDEX IF NOT EXISTS idx_activity_person ON activity(person_id,occurred_at);
CREATE TABLE IF NOT EXISTS person_aliases(account_id TEXT NOT NULL REFERENCES social_accounts(id),provider_id TEXT NOT NULL,person_id TEXT NOT NULL REFERENCES people(id),PRIMARY KEY(account_id,provider_id));
CREATE TABLE IF NOT EXISTS rate_windows(account_id TEXT NOT NULL REFERENCES social_accounts(id),window_start TEXT NOT NULL,count INTEGER NOT NULL,PRIMARY KEY(account_id,window_start));
CREATE TABLE IF NOT EXISTS provider_recipients(message_id TEXT PRIMARY KEY REFERENCES messages(id),provider_id TEXT NOT NULL);
